version: '3.12'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - magistral/docker.env
    volumes:
      - .:/srv/app
    ports:
      - '0.0.0.0:3000:3000'
    command: python manage.py runserver 0.0.0.0:3000

volumes:
  static-data: